remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome: ./introduction
    - Setup: ./setup
  - Intro to GIT:
    - Intro to Command Line: git_lessons/git_command_line
    - Github Creating: git_lessons/git_repo_create
    - GIT on Command Line: git_lessons/using_git
    - Work GIT - Workflow: git_lessons/git_workflow
    - GITing Out of Trouble: git_lessons/git_trouble
  - Intro to Juypter Notebooks and reproducibility:
    - Intro to Jupyter: jupyter_lessons/jupyter_intro
    - Publishing and Archiving: jupyter_lessons/archiving
